import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../Components/Contact'
import Navbar from '../Components/Navbar'
import Header from '../Components/Header'
import { BlogContext } from '../Context/BlogContext'
import { useContext } from 'react'
export default function Home() {
  const {posts, users} = useContext(BlogContext)
  return (
    <div className={styles.container}>
      <Head>
        <title>جمعية العمل الرشيد</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <header className="flex justify-between p-4">
        <img src='/logo.png' id="logo" alt="logo" />
        <Header/>
      </header>
      <main className={styles.main}>
        <h1 className=' font-bold underline'>
          Welcome to <a>جمعية العمل الرشيد</a>
        </h1>
        <Navbar/>
        <Contact/>
        <div> 
        <h1>
        أهداف الجمعية:
        </h1>
          <ul className="goal" >
            <li>المساهمة في تقليص مظاهر التلوث.</li>
            <li>المساهمة في جعل مساحات الثقافة والترفيه متاحة لجميع فئات المجتمع.</li>
            <li>نشر ثقافة الرسكلة وتثمين النفايات.</li>
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/ibtihel-ben-salah/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            ibtihel ben salah
          </span>
        </a>
      </footer>
    </div>
  )
}
