import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../Components/Contact'
import Navbar from '../Components/Navbar'
import Header from '../Components/Header'
import Goals from '../Components/Goals'
import { BlogContext } from '../Context/BlogContext'
import { useContext } from 'react'
export default function Home() {
  const {posts, users} = useContext(BlogContext)
  return (
    <div className='scroll-smooth p-5 bg-gray-light'>
      <Head>
        <title>جمعية العمل الرشيد</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <header className="h-screen">
        <Header/>
      </header>
        <Goals/>
        <Navbar/>
        <Contact/>
      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/ibtihel-ben-salah/"
          target="_blank"
          rel="ibtihel ben salah"
        >
          Powered by{' '}
          <span className={styles.logo}>
            ibtihel ben salah
          </span>
        </a>
      </footer>
    </div>
  )
}
