import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from './Componants/Contact'
import Navbar from './Componants/Navbar'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>جمعية العمل الرشيد</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <header>
        <img src='/logo.png' id="logo" alt="logo" />
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>جمعية العمل الرشيد</a>
        </h1>
        <Navbar/>
        <Contact/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/ibtihel-ben-salah/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            ibtihel ben salah
          </span>
        </a>
      </footer>
    </div>
  )
}
